### ISSUE TITLE
Cannot run `tsc` due to importing `.html` file in `.ts`

### ISSUE THREAD

**Issue by foray1010** [foray1010/web-containers#19]
`tsc` is ts's compiler, when you try to run it now, you will get following error:

```
src/index.ts:1:17 - error TS2307: Cannot find module './components/App.html'.

1 import App from './components/App.html'
                  ~~~~~~~~~~~~~~~~~~~~~~~
```

related issue: https://github.com/Microsoft/TypeScript/issues/14419

possible solutions:
- https://github.com/cevek/ttypescript
- https://github.com/TypeStrong/ts-loader (need to use webpack)

cc @nickccm1122

**Comment by nickccm1122** [comment]
created a #21
